apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"app","app.kubernetes.io/name":"app"},"name":"app"}}
  labels:
    app.kubernetes.io/instance: app
    app.kubernetes.io/name: app
  name: app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"user-api","namespace":"app"}}
  name: user-api
  namespace: app
spec:
  replicas: 1
  serviceName: user-api
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      name: user-api-pod
      labels:
        app: user-api
    spec:
      imagePullSecrets:
        - name: aliyun-docker
      containers:
        - name: user-api-container
          image: registry.cn-hangzhou.aliyuncs.com/thy-k8s/user-api:latest
          resources:
            limits:
              memory: "520Mi"
              cpu: "200m"
          ports:
            - containerPort: 8001
          env:
            - name: JAVA_OPTS
              value: "-javaagent:/home/java/skywalking-agent/skywalking-agent.jar -Xms256m -Xmx512m"
            - name: APP_OPTS
              value: >
                -Dspring.profiles.active=prod 
                -Dspring.cloud.nacos.discovery.server-addr=nacos-headless.nacos 
                -Dspring.cloud.nacos.discovery.namespace=19a0fa32-ed2e-40f1-a1e1-aae8c81d8cf8 
                -Dskywalking.agent.service_name=user-api 
                -Dskywalking.collector.backend_service=10.11.38.190:11800
          volumeMounts:
            - name: log
              mountPath: "/data/logs/user-api/"
  volumeClaimTemplates:
    - metadata:
        name: log
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: user-api
  namespace: app
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"name":"user-api-service","namespace":"app"}}
spec:
  type: NodePort
  selector:
    app: user-api
  ports:
    - name: http
      protocol: TCP
      nodePort: 30088
      port: 80
      targetPort: 8001
