server:
  port: 9002
  shutdown: graceful

spring:
  profiles:
    active: dev
  application:
    name: record-web
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 10.11.38.190:8849
        group: DEFAULT_GROUP
        namespace: 69b65d3b-77d2-481a-8f99-1643488f90fa
      config:
        group: DEFAULT_GROUP
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:${spring.application.name}.yml


snowflake:
  redisson:
    mode: ${redisson.mode}
    cluster:
      node-address: ${redisson.cluster.node-address}
      password: ${redisson.cluster.password}
  # single:
  #  address: ${redisson.single.address}
  #  password: ${redisson.single.password}
  #  database: ${redisson.single.database}


mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback-spring.xml


management:
  server:
    port: 9484
  endpoints:
    web:
      exposure:
        include: '*'