server:
  port: 8001

spring:
  profiles:
    active: dev
  application:
    name: user-api
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
        group: DEFAULT_GROUP
        namespace: public
      config:
        group: DEFAULT_GROUP
        server-addr: localhost:8848
  config:
    import:
      - optional:nacos:${spring.application.name}.yml

web:
  feign:
    user: user-web

logging:
  config: classpath:logback-spring.xml
