server:
  port: 9001
  shutdown: graceful

spring:
  profiles:
    active: dev
  application:
    name: user-web
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 10.11.38.190:8849
        group: DEFAULT_GROUP
        namespace: 69b65d3b-77d2-481a-8f99-1643488f90fa
      config:
        group: DEFAULT_GROUP
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
  config:
    import:
      - optional:nacos:${spring.application.name}.yml

redisson:
  mode: cluster
  cluster:
    ## 自动拓扑发现剩余节点
    node-address: "redis://redis.redis:6379"
    password: 123456


snowflake:
  redisson:
    node-address: ${redisson.cluster.address}
    password: ${redisson.cluster.password}


mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback-spring.xml
