server:
  port: 9001

spring:
  profiles:
    active: dev
  application:
    name: user-web
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 192.168.222.129:8849
        group: DEFAULT_GROUP
        namespace: public
      config:
        group: DEFAULT_GROUP
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - optional:nacos:${spring.application.name}.yml


snowflake:
  redisson:
    address: ${redisson.single.address}
    password: ${redisson.single.password}
    database: ${redisson.single.database}


mybatis-plus:
  global-config:
    banner: false
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback-spring.xml
