redisson:
  mode: cluster
  cluster:
    ## 自动拓扑发现剩余节点
    node-address: "redis://redis.redis:6379"
    password: 123456

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.11.38.190:3307/user_test?tinyInt1isBit=false&nullCatalogMeansCurrent=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      initialSize: 5
      logAbandoned: true
      maxActive: 10
      maxWait: 61000
      minEvictableIdleTimeMillis: 26200000
      minIdle: 1
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 28000
      validationQuery: SELECT 1
